# docker-compose -f docker-compose-environment-ollama.yml up -d
version: '3'
services:
  # 对话模型
  ollama:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/ollama:0.5.10
    container_name: ollama-server
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - ollama-network

  # Redis（专属此系统）
  redis-ollama:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/redis:6.2
    container_name: redis-ollama
    restart: always
    hostname: redis-ollama
    privileged: true
    ports:
      - 26379:6379   # 避免和第一份 16379 冲突
    volumes:
      - ./ollama-redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - ollama-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "redis-ollama", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis 管理工具
  redis-admin-ollama:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/redis-commander:0.8.0
    container_name: redis-admin-ollama
    hostname: redis-admin-ollama
    restart: always
    ports:
      - 18081:8081   # 避免和第一份 8081 冲突
    environment:
      - REDIS_HOSTS=local:redis-ollama:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - ollama-network
    depends_on:
      redis-ollama:
        condition: service_healthy

  # 向量数据库
  vector_db:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/pgvector:v0.5.0
    container_name: vector-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai-rag-knowledge
      - PGPASSWORD=postgres
    volumes:
      - ./ollama-pgvector/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '25432:5432'  # 避免和第一份 15432 冲突
    healthcheck:
      test: "pg_isready -U postgres -d ai-rag-knowledge"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
